services:
  backend:
    image: c_webapp_backend_dev
    build: .
    container_name: c_webapp_backend_dev
    restart: always

    working_dir: /cifrotech_webapp_

    environment:
      MODE: dev
      SP: /run/secrets/app_env

    volumes:
      - .:/cifrotech_webapp_
      - D:/cifrotech_env/.env:/run/secrets/app_env:ro

    ports:
      - "5000:5000"

    command: uvicorn main:app --host 0.0.0.0 --port 5000

    depends_on:
      - redis
      - postgres


  redis:
    image: redis:latest
    container_name: c_webapp_redis_dev
    restart: always

    ports:
      - "6379:6379"


  postgres:
    image: postgres:latest
    container_name: c_webapp_postgres_dev
    restart: always

    env_file:
      - D:/cifrotech_env/.env

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: