"""empty message

Revision ID: 30377e4455e4
Revises: d7c9971d0469
Create Date: 2025-03-31 13:31:21.797355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30377e4455e4'
down_revision: Union[str, None] = 'd7c9971d0469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producttype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('kind', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('kind_tsv', postgresql.TSVECTOR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('product_type_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_type_id')
    op.drop_table('producttype')
    # ### end Alembic commands ###
