"""empty message

Revision ID: 459c72fd7133
Revises: 30377e4455e4
Create Date: 2025-03-31 13:34:38.685423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '459c72fd7133'
down_revision: Union[str, None] = '30377e4455e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producttype', 'kind_tsv',
               existing_type=postgresql.TSVECTOR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producttype', 'kind_tsv',
               existing_type=postgresql.TSVECTOR(),
               nullable=False)
    # ### end Alembic commands ###
