"""empty message

Revision ID: a839a752e0e1
Revises: 459c72fd7133
Create Date: 2025-03-31 13:37:25.129632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a839a752e0e1'
down_revision: Union[str, None] = '459c72fd7133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_kind_tsv', 'producttype', ['kind_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_kind_tsv', table_name='producttype', postgresql_using='gin')
    # ### end Alembic commands ###
