"""empty message

Revision ID: d7c9971d0469
Revises: 87887a8ae260
Create Date: 2025-03-30 19:07:41.812590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c9971d0469'
down_revision: Union[str, None] = '87887a8ae260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendorstock', sa.Column('source_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendorstock', 'source_data')
    # ### end Alembic commands ###
